
# Single QUA script generated at 2024-06-19 16:02:16.547108
# QUA library version: 1.1.7

from qm.qua import *

with program() as prog:
    v1 = declare(int, value=0)
    v2 = declare(fixed, )
    v3 = declare(fixed, )
    v4 = declare(fixed, )
    v5 = declare(fixed, )
    v6 = declare(fixed, )
    v7 = declare(fixed, )
    v8 = declare(fixed, )
    v9 = declare(fixed, )
    v10 = declare(fixed, )
    v11 = declare(fixed, )
    v12 = declare(fixed, )
    v13 = declare(fixed, )
    v14 = declare(fixed, )
    v15 = declare(fixed, )
    with infinite_loop_():
        pause()
        align()
        measure("measure", "readout_element", None, integration.full("x", v2, ""), integration.full("y", v3, ""))
        assign(v4, (v2+v3))
        r2 = declare_stream()
        save(v2, r2)
        r3 = declare_stream()
        save(v3, r3)
        r4 = declare_stream()
        save(v4, r4)
        measure("measure", "readout_element", None, integration.full("x", v8, ""), integration.full("y", v9, ""))
        assign(v10, (v8+v9))
        r8 = declare_stream()
        save(v8, r8)
        r9 = declare_stream()
        save(v9, r9)
        r10 = declare_stream()
        save(v10, r10)
        wait(50, )
        measure("measure", "readout_element", None, integration.full("x", v5, ""), integration.full("y", v6, ""))
        assign(v7, (v5+v6))
        r5 = declare_stream()
        save(v5, r5)
        r6 = declare_stream()
        save(v6, r6)
        r7 = declare_stream()
        save(v7, r7)
        measure("measure", "readout_element", None, integration.full("x", v11, ""), integration.full("y", v12, ""))
        assign(v13, (v11+v12))
        r11 = declare_stream()
        save(v11, r11)
        r12 = declare_stream()
        save(v12, r12)
        r13 = declare_stream()
        save(v13, r13)
        assign(v14, (v4-v7))
        r14 = declare_stream()
        save(v14, r14)
        assign(v15, (v10-v13))
        r15 = declare_stream()
        save(v15, r15)
        assign(v1, (v1+1))
        r1 = declare_stream()
        save(v1, r1)
    with stream_processing():
        r1.buffer(1).save("dummy_squence2_shots")
        r2.buffer(1).save("dummy_readout2__qubit1__reference__sensor1_I_buffer")
        r3.buffer(1).save("dummy_readout2__qubit1__reference__sensor1_Q_buffer")
        r4.buffer(1).save("dummy_readout2__qubit1__reference__sensor1_IQ_buffer")
        r5.buffer(1).save("dummy_readout2__qubit1__read__sensor1_I_buffer")
        r6.buffer(1).save("dummy_readout2__qubit1__read__sensor1_Q_buffer")
        r7.buffer(1).save("dummy_readout2__qubit1__read__sensor1_IQ_buffer")
        r8.buffer(1).save("dummy_readout2__qubit2__reference__sensor1_I_buffer")
        r9.buffer(1).save("dummy_readout2__qubit2__reference__sensor1_Q_buffer")
        r10.buffer(1).save("dummy_readout2__qubit2__reference__sensor1_IQ_buffer")
        r11.buffer(1).save("dummy_readout2__qubit2__read__sensor1_I_buffer")
        r12.buffer(1).save("dummy_readout2__qubit2__read__sensor1_Q_buffer")
        r13.buffer(1).save("dummy_readout2__qubit2__read__sensor1_IQ_buffer")
        r14.buffer(1).save("dummy_readout2__qubit1__diff_buffer")
        r15.buffer(1).save("dummy_readout2__qubit2__diff_buffer")


config = None

loaded_config = None

